core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<slug:category_slug>/', views.StoreView.as_view(),
         name='store_by_category'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('payment/create-payment-intent', views.create_payment),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

# Serving static files / files uploaded by user during development

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.urls import reverse
import uuid


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('core:store_by_category', kwargs={'category_slug': self.slug})


class Product(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    category = models.ForeignKey(
        Category, related_name='products', on_delete=models.SET_NULL, blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Order(models.Model):
    transaction_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return f'Order #{self.transaction_id}'

    def get_total(self):
        return sum(item.get_item_cost() for item in self.order_items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, related_name='order_items', on_delete=models.CASCADE)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} of {self.item.name}'

    def get_item_cost(self):
        return self.item.price * self.quantity

class Cart(object):
    def __init__(self, request):
        self.session = request.session
        cart = self.session.get(settings.CART_SESSION_KEY)
        if not cart:
            cart = self.session[settings.CART_SESSION_KEY] = {}
        self.cart = cart

    def __iter__(self):
        ids = self.cart.keys()
        products = Product.objects.filter(id__in=ids)
        cart = self.cart.copy()
        for product in products:
            cart[str(product.id)]['product'] = product
        for item in cart.values():
            item['total_price'] = Decimal(
                item['product'].price) * item['quantity']
            yield item

    def __len__(self):
        return sum(item['quantity'] for item in self.cart.values())

    def add(self, item, quantity=1, override=False):
        product_id = str(item.id)
        if product_id not in self.cart:
            self.cart[product_id] = {
                'quantity': quantity}
        elif override:
            self.cart[product_id]['quantity'] = quantity
        else:
            self.cart[product_id]['quantity'] += quantity
        self.save()

    def remove(self, item):
        product_id = str(item.id)
        if product_id in self.cart:
            del self.cart[product_id]
            self.save()

    def clear(self):
        del self.session[settings.CART_SESSION_KEY]
        self.save()

    def save(self):
        self.session.modiefied = True

    def get_total_price(self):
        return sum(Decimal(item['total_price']) for item in self.cart.values())

core/forms.py
from django import forms

from .widgets import NumberStepperWidget


class ProductQuantityForm(forms.Form):
    quantity = forms.IntegerField(
        required=False, initial=1, label='', widget=NumberStepperWidget(attrs={'min': 1, 'max': 10}))


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['first_name', 'last_name', 'street_address_line1', 'street_address_line2',
                  'city', 'state', 'country', 'zip_code']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'


class ShippingForm(AddressForm):
    email = forms.EmailField(required=False)
    use_default_shipping = forms.BooleanField(
        required=False, initial=True, label='Use default shipping address')
    set_as_default = forms.BooleanField(
        required=False, initial=True, label='Save as default shipping address')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['use_default_shipping'].widget.attrs['class'] = 'form-control-input'


class BillingForm(AddressForm):
    same_as_shipping = forms.BooleanField(
        required=False, initial=True, label='Billing address is the same as shipping address')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['same_as_shipping'].widget.attrs['class'] = 'form-control-input'

core/views.py
from django.conf import settings
from django.shortcuts import reverse, render, redirect, get_object_or_404
from django.contrib import messages
from django.views.generic import View, ListView, DetailView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponseForbidden, JsonResponse

from .models import Product, Category, OrderItem, Order, Cart, Address

import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


class StoreView(ListView):
    template_name = 'store.html'

    def get_queryset(self):
        if self.kwargs.get('category_slug'):
            category = get_object_or_404(
                Category, slug=self.kwargs.get('category_slug'))
            return Product.objects.filter(category=category)
        else:
            return Product.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['category_slug'] = self.kwargs.get('category_slug')
        return context


class ProductDisplay(DetailView):
    model = Product
    template_name = 'product.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ProductQuantityForm()
        return context


class ProductQuantity(SingleObjectMixin, FormView):
    model = Product
    template_name = 'product.html'
    form_class = ProductQuantityForm

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        quantity = form.cleaned_data.get('quantity')
        cart = self.request.session.get('shopping_cart')
        order_item, created = OrderItem.objects.get_or_create(item=self.object)
        if not cart:
            cart = self.request.session['shopping_cart'] = {}

        if str(order_item.item.id) in cart.keys():
            cart[str(order_item.item.id)] = cart[str(
                order_item.item.id)] + quantity
            order_item.quantity += quantity
            order_item.save()
            messages.info(self.request, 'Item quantity updated')
        else:
            cart[str(order_item.item.id)] = quantity
            order_item.quantity = quantity
            order_item.save()
            cart[order_item.item.id] = quantity
            messages.info(self.request, 'Item added to cart')

        self.request.session['shopping_cart'] = cart
        # Gotcha: Session is NOT modified, because this alters
        # request.session['shopping_cart'] instead of request.session.
        # self.request.session['shopping_cart'][str(order_item.item.id)]
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('core:product', kwargs={'slug': self.object.slug})


class ProductDetailView(View):
    def get(self, request, *args, **kwargs):
        view = ProductDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = ProductQuantity.as_view()
        return view(request, *args, **kwargs)


class CartView(DetailView):
    model = OrderItem
    template_name = 'cart.html'


class CheckoutView(View):
    def get(self, request, *args, **kwargs):
        cart = Cart(request)
        context = {
            'cart': cart,
            'shipping_form': CheckoutForm()
        }
        if request.user.is_authenticated:
            shipping_address_qs = Address.objects.filter(
                user=request.user, address_type='S', default=True)
            if shipping_address_qs.exists():
                context.update(
                    {'default_shipping_address': shipping_address_qs[0]})
        return render(request, 'checkout.html', context)

    def post(self, request, *args, **kwargs):
        cart = Cart(request)
        shipping_form = CheckoutForm(request.POST)
        if shipping_form.is_valid():
            cd = shipping_form.cleaned_data
            shipping_address = shipping_form.save(commit=False)
            shipping_address.user = request.user
            if (cd.get('set_default_shipping')):
                shipping_address.default = True
            shipping_address.save()

            # Create order
            order = Order.objects.create(
                email=request.user.email, shipping_address=shipping_address)
            for item in cart:
                OrderItem.objects.create(
                    order=order, item=item['product'], quantity=item['quantity'])
            cart.clear()

        # Redirect to payment
        return redirect('core:payment')


def create_payment(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    amount = int(order.get_total() * 100)
    try:
        intent = stripe.PaymentIntent.create(
            amount=amount, currency='usd', payment_method_types=['card'])
        return JsonResponse({'client_secret': intent['client_secret']})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=403)


class PaymentView(View):
    def get(self, request, *args, **kwargs):
        order_id = request.session.get('order_id')
        order = get_object_or_404(Order, id=order_id)
        context = {'billing_form': BillingAddressForm()}
        if order.shipping_address:
            context['shipping_address'] = order.shipping_address
        return render(request, 'payment.html', context)

core/templates/address-form.html
<div class="form-group row">
  <div class="col">
    {{ form.email.label_tag }}
    {{ form.email }}
  </div>
</div>
<div class="row">
  <div class="form-group col">
    {{ form.first_name.label_tag }}
    {{ form.first_name }}
  </div>
  <div class="form-group col">
    {{ form.last_name.label_tag }}
    {{ form.last_name }}
  </div>
</div>
<div class="form-group row">
  <div class="col">
    {{ form.street_address_line1.label_tag }}
    {{ form.street_address_line1 }}
  </div>
</div>
<div class="form-group row">
  <div class="col">
    {{ form.street_address_line2.label_tag }}
    {{ form.street_address_line2 }}
  </div>
</div>
<div class="row">
  <div class="form-group col">
    {{ form.city.label_tag }}
    {{ form.city }}
  </div>
  <div class="form-group col">
    {{ form.state.label_tag }}
    {{ form.state }}
  </div>
</div>
<div class="row">
  <div class="form-group col">
    {{ form.country.label_tag }}
    {{ form.country }}
  </div>
  <div class="form-group col">
    {{ form.zip_code.label_tag }}
    {{ form.zip_code }}
  </div>
</div>
<div class="form-check">
  {{ shipping_form.set_as_default }}
  {{ shipping_form.set_as_default.label_tag }}
</div>

core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>
      {% block head_title %}
      {% endblock head_title %}
    </title>
    
    {% block extra_head %}
    {% endblock extra_head %}
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <script type="text/javascript">
      const getCookie = (name) => {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === name + '=') {
              cookieValue = decodeURIComponent(
                cookie.substring(name.length + 1)
              );
              break;
            }
          }
        }
        return cookieValue;
      };
      const csrftoken = getCookie('csrftoken');
    </script>
  </head>
  <body>
    <nav>
      {% include 'navbar.html' %}
    </nav>  
    
    {% block content %}
    {% endblock content %}
    
    <script type="text/javascript" src="https://js.stripe.com/v3/"></script>

    {% block extra_scripts %}
    {% endblock extra_scripts %}
  </body>
</html>

core/templates/cart.html
{% extends "base.html" %} 

{% block content %}
  <main class="container">
    <h2>Shopping Cart</h2>
    <div class="row">
      <div class="col-md-8">
        <ul class="list-group">
          {% for item in cart %}
            {% with product=item.product %}
              <li class="list-group-item">
                <div class="row flex-nowrap align-items-start">
                  <div class="col">
                    <img class="card-img-top thumbnail" src="{{ item.product.imageURL }}" />
                  </div>
                  <div class="col">
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.price }}</p>
                  </div>
                  <div class="col">{{ item.quantity }}</div>
                  <div class="col">{{ item.total_price }}</div>
                  <form action="{% url "core:remove_from_cart" product.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn-remove" aria-label="Remove">
                      <i class="fas fa-times-circle"></i>
                    </button>
                  </form>
                </div>
              </li>
            {% endwith %}
          {% endfor %}
        </ul>
      </div>
      <div class="col-md-4">
        {% include 'order-summary.html' %}
        <a href="{% url 'core:checkout' %}" class="btn btn-primary mt-3">CONTINUE TO CHECKOUT</a>
      </div>
    </div>
  </main>
{% endblock content %}

core/templates/checkout.html
{% extends "base.html" %} 

{% load static %} 

{% block content %}
  <main class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-8">
            <h4 class="mb-3">Shipping Address</h4>
            <form
              method="post"
              class="needs-validation"
              novalidate
            >
              {% csrf_token %}
              {% if default_shipping_address %}
                <div class="form-check">
                  {{ shipping_form.use_default_shipping }}
                  {{ shipping_form.use_default_shipping.label_tag }}
              </div>
                <div id="hideable-shipping-address">
                  <p>
                    {{ default_shipping_address.first_name }} {{ default_shipping_address.last_name }}
                  </p>
                  <p>
                    {{ default_shipping_address.street_address_line1|truncatechars:10 }}
                  </p>
                  {% if default_shipping_address.street_address_line2 %}
                    <p>
                      {{ default_shipping_address.street_address_line2|truncatechars:10 }}
                    </p>
                  {% endif %}
                  <p>
                    {{ default_shipping_address.city  }}, {{ default_shipping_address.state }} {{ default_shipping_address.zip_code }}
                  </p>
                </div>
              {% endif %}
              <div class="hideable-shipping-form mt-3"
                {% if default_shipping_address %}
                  hidden
                {% endif %}
                  >
                {% with form=shipping_form %}
                  {% include 'address-form.html' %}
                {% endwith %}
                </div>
              <button type="submit" class="btn btn-primary mt-3">
                CONTINUE TO PAYMENT
              </button>
            </form>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        {% include 'order-summary.html' %}
      </div>
    </div>
  </main>
{% endblock %}

{% block extra_scripts %}
  <script type="text/javascript" src="{% static 'js/addressToggler.js' %}"></script>
{% endblock extra_scripts %}

core/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" role="navigation">
  <button data-toggle="collapse" class="navbar-toggler" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-between">
    <a href="" class="navbar-brand">Hidden Brand</a>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a href="" class="nav-link">
          <i class="fas fa-shopping-cart"></i>
        </a>
      </li>
      <li class="nav-item">
        <a href="" class="nav-link">
          <span class="">Log Out</span>
        </a>
      </li>
    </ul>
  </div>
</nav>

core/templates/order-summary.html
<div class="d-flex flex-column-reverse p-3 bg-light">
  {% if 'cart' not in request.path %}
    <div class="mt-5">
      <h6 class="mb-3 font-weight-bold">
        Items in your cart ({{ cart|length }})
      </h6>
      <ul class="list-group list-group-flush">
        {% for item in cart %}
          {% with product=item.product %}
            <li class="list-group-item px-0 bg-transparent">
              <div class="row flex-nowrap align-items-start">
                <div class="col">
                  <img class="card-img-top thumbnail" src="{{ product.imageURL }}" />
                </div>
                <div class="col">
                  <p>{{ product.name }}</p>
                </div>
                <div class="col">
                  <p>Qty: {{ item.quantity }}</p>
                  <p>${{ item.total_price }}</p>
                </div>
              </div>
            </li>
          {% endwith %}
        {% endfor %}
      </ul>
    </div>
  {% endif %}
  <ul class="list-group list-group-flush">
    <li class="list-group-item border-0 bg-transparent text-center">
      <h6 class="font-weight-bold">Order Summary</h6>
    </li>
    <li class="list-group-item d-flex justify-content-between bg-transparent">
      <span>Subtotal</span>
      <span>${{ cart.get_total_price|floatformat:2 }}</span>
    </li>
    <li class="list-group-item d-flex justify-content-between bg-transparent">
      <span>Shipping</span>
      <span>Free</span>
    </li>
    <li class="list-group-item d-flex justify-content-between bg-transparent">
      <span>Sales Tax</span>
      <span>$0.00</span>
    </li>
    <li
      class="list-group-item d-flex justify-content-between font-weight-bold bg-transparent"
    >
      <span>Total</span>
      <span>${{ cart.get_total_price|floatformat:2 }}</span>
    </li>
  </ul>
</div>

core/templates/payment.html
{% extends 'base.html' %}

{% load static %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/stripe.css' %}" />
{% endblock extra_head %}
  
{% block content %}
  <main class="container py-5 pl-5 pr-2">
    <div class="row">
      <div class="col-md-7">
    <h4>Add a Payment Method</h4>
    {% if card %}
      <div>
            <div class="form-check">
              <input type="checkbox" id="use_default_card" name="use_default_card" class="form-check-input">
              <label for="use_default_card" class="form-check-label">
                Use default card: **** **** **** {{ card.last4 }} 
              <span>Exp: {{ card.exp_month }}/{{ card.exp_year }}</span>
              </label>
        </div>
      </div>
    {% endif %}
    <form method="post" id="stripe-payment-form">
      {% csrf_token %}
          <div id="card-element" class="StripeElement StripeElement--empty mt-5 mb-3">
            <!-- Stripe.js injects the Card Element -->
      </div>
          <button type="submit" class="btn btn-primary">
            <div id="spinner" class="spinner hidden"></div>
            <span id="btn-text">PLACE ORDER</span>
          </button>
          <p id="card-error" role="alert"></p>
          <p class="result-message hidden">
            Payment succeeded. See result in your
            <a href="" target="_blank">Stripe dashboard.</a>
          </p>
    </form>
        {% if shipping_address %}
          <div class="form-check">
            <input
              type="checkbox"
              id="same_as_shhipping"
              name="same_as_shipping"
              class="form-check-input"
              checked
            />
            <label for="same_as_shipping" class="form-check-label">
              Billing address is the same as shipping address
            </label>
    </div>
          <div id="hideable-shipping-address">
      <p>{{ shipping_address.first_name }} {{ shipping_address.last_name }}</p>
      <p>{{ shipping_address.street_address_line1|truncatechars:10 }}</p>
      {% if shipping_address.street_address_line2 %}
        <p>{{ shipping_address.street_address_line2|truncatechars:10 }}</p>
      {% endif %}
      <p>{{ shipping_address.city }}, {{ shipping_address.state}} {{ shipping_address.zip_code }}</p>
          </div>
    {% endif %}
        <form method="post" class="hideable-billing-form needs-validation" novalidate hidden>
          {% csrf_token %}
          {% with form=billing_form %}
            {% include 'address-form.html' %}
          {% endwith %}
          <button type="submit" class="btn btn-primary">
            PLACE ORDER
          </button>
    </form>
  </main>
{% endblock content %}

{% block extra_scripts %}
  <script type="text/javascript" src="{% static 'js/stripe.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/billingAddressToggle.js' %}"></script>
{% endblock extra_scripts%}

core/templates/product.html
{% extends "base.html" %}

{% load static %} 

{% block content %}
  <main class="p-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <img
            src="{{ object.imageURL }}"
            class="w-100"
            alt="{{ object.name }}"
          />
        </div>
        <div class="col-md-6 pl-5 pr-5">
          <h3 class="lead font-weight-bold">{{ object.name }}</h3>
          <p>{{ object.description }}</p>
          {% if object.discount_price %}
            <p class="lead">
              <span><del>{{ object.price }}</del></span>
              <span>${{ object.discount_price }}</span>
            </p>
          {% else %}
            <span class="lead">${{ object.price }}</span>
          {% endif %}
          <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary btn-lg">
              ADD TO CART
            </button>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock content %} 

{% block extra_scripts %}
  <script type="text/javascript" src="{% static 'js/numberStepper.js' %}"></script>
{% endblock extra_scripts %}

core/templates/store.html
{% extends "base.html" %}

{% block content %}
  <main>
    <header class="jumbotron jumbotron-fluid mb-0 px-5">
      <h1 class="display-3">The Character Market</h1>
      <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent</p>
    </header>
    <nav class="navbar navbar-expand-lg navbar-light">

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse">

        <!-- Product categories -->
        <ul class="navbar-nav w-100 justify-content-center">
          <li class="category">
            <a href="/" class="nav-link
              {% if not category_slug %}
                active
              {% endif %}"
            >
              All
            </a>
          </li>
          {% for category in categories %}
            <li class="category
              {% if category.slug == category_slug %}
                active
              {% endif %}"
            >
              <a href="{{ category.get_absolute_url }}" class="nav-link">{{ category.name }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </nav>
    <hr class="mt-0" />
    <section class="container">
      <div class="row">
        {% for product in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">
            <a href="{% url 'core:product' product.slug %}">
              <div class="card">
                <div class="overlay">
                  <img class="card-img-top thumbnail" src="{{ product.imageURL }}" />
                </div>
                <div class="card-body text-center">
                  <h6><strong>{{ product.name }}</strong><h6>
                  <h6>${{ product.price }}</h6>
                </div>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    </section>
  <main>
{% endblock content %}